import { writeFileSync } from 'node:fs';
import { test,expect } from '@playwright/test';

test('live-only workspace, provider failure and manual Discord approval gate',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
 await page.goto('/');
 await expect(page.locator('html')).toHaveAttribute('lang','en');
 await expect(page.getByRole('button',{name:'Create a plan'})).toBeDisabled();
 await expect(page.getByRole('combobox')).toHaveCount(0);
 await expect(page.getByText(/SCRIPTED|Démo scripted/)).toHaveCount(0);
 const rejected=await page.request.post('/api/plan',{data:{provider:'scripted',prompt:'test',clientId:crypto.randomUUID(),seq:1}});expect(rejected.status()).toBe(400);
 const rejectedChat=await page.request.post('/api/chat',{data:{provider:'scripted',message:'test'}});expect(rejectedChat.status()).toBe(400);
 await page.getByRole('button',{name:'Discord message',exact:true}).click();
 await page.getByLabel('Discord message',{exact:true}).fill('Test Orbit : rendez-vous à 18 h.');
 await page.getByRole('button',{name:'Prepare for approval'}).click();
 const manual=page.getByTestId('card-post_discord-0');
 await expect(page.getByText('Et la prochaine fois ?',{exact:true})).toHaveCount(0);
 await expect(page.getByText(/Préférence enregistrée/)).toHaveCount(0);
 expect((await page.request.post('/api/ask',{data:{question:'Quand ?'}})).status()).toBe(404);
 await expect(manual.getByText('Test Orbit : rendez-vous à 18 h.',{exact:true})).toBeVisible();
 await manual.getByRole('button',{name:/^Approve and (send|create)$/}).click();
 await expect(page.getByRole('alert')).toContainText('External actions are disabled');
 await expect(manual.getByText('To review',{exact:true})).toBeVisible();
 // Only readiness is mocked. No provider or publishing request leaves the test server.
 await page.route('**/api/status',async route=>{const response=await route.fetch();await route.fulfill({json:{...await response.json(),liveReady:true}});});
 await page.route('**/api/plan',route=>{expect(route.request().postDataJSON().provider).toBe('backboard');return route.fulfill({status:503,json:{error:'Fournisseur indisponible. Réessayez.'}});});
 await page.reload();await expect(manual).toBeVisible();
 await page.getByLabel('Event idea',{exact:true}).fill('Un atelier pour débutants');
 await page.getByRole('button',{name:'Create a plan'}).click();
 await expect(page.getByRole('alert')).toContainText('Provider unavailable');
 await expect(manual).toBeVisible();await expect(page.getByRole('button',{name:/scripted/i})).toHaveCount(0);
 await page.getByRole('button',{name:/Clear 1 proposals/}).click();await expect(manual).toHaveCount(0);
 await page.getByRole('button',{name:'Chat with my agent',exact:true}).click();
 await expect(page.getByRole('combobox')).toHaveCount(0);
 await page.route('**/api/chat',route=>{expect(route.request().postDataJSON().provider).toBe('backboard');return route.fulfill({status:503,json:{error:'Chat is unavailable. Try again.'}});});
 await page.getByLabel('Your message',{exact:true}).fill('Rédige un message à mon équipe.');
 await page.getByRole('button',{name:'Send to agent',exact:false}).click();
 await expect(page.getByRole('alert')).toContainText('Chat is unavailable');
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(errors).toEqual([]);
});

test('chat draft becomes an unapproved Discord card without sending',async({page})=>{
 const id=crypto.randomUUID();
 const conversation={version:1,id,revision:1,provider:'backboard',turns:[{message:'Rédige une annonce',at:new Date().toISOString(),reply:{text:'Voici le brouillon.',draft:{title:'Annonce à relire',text:'Bonjour à toute l’équipe !'},sources:[]}}]};
 writeFileSync(`.data/browser-test/chat-${id}.json`,JSON.stringify(conversation));
 await page.goto('/');await page.evaluate(id=>sessionStorage.setItem('orbit-chat',id),id);await page.reload();
 await page.getByRole('button',{name:'Chat with my agent',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Annonce à relire'})).toBeVisible();
 const before=await (await page.request.get('/api/log')).json();
 await page.getByRole('button',{name:'Prepare for Discord approval',exact:true}).click();
 const card=page.getByTestId('card-post_discord-0');
 await expect(card.getByText('Bonjour à toute l’équipe !',{exact:true})).toBeVisible();
 await expect(card.getByText('To review',{exact:true})).toBeVisible();
 const after=await (await page.request.get('/api/log')).json();
 const newLogs=after.filter((entry:{id:string})=>!before.some((old:{id:string})=>old.id===entry.id));
 expect(newLogs.map((entry:{event:string})=>entry.event)).toEqual(['propose']);
 const stale=await page.request.post(`/api/chat/${id}/discord-draft`,{data:{expectedRevision:2,turnIndex:0}});expect(stale.status()).toBe(400);
 await card.getByRole('button',{name:/^Approve and (send|create)$/}).click();await expect(page.getByRole('alert')).toContainText('External actions are disabled');
 await page.getByRole('button',{name:'Chat with my agent',exact:true}).click();await expect(page.getByRole('heading',{name:'Annonce à relire'})).toBeVisible();
});

test('fact errors stay inline and missing LinkedIn URL does not block Calendar or Discord',async({page})=>{
 const {normalize}=await import('../../src/core/model');
 const {fixturePlan,initialFacts}=await import('../../src/core/fixtures');
 const id=crypto.randomUUID();
 const result=normalize(fixturePlan(),{id,requestId:id,now:new Date().toISOString(),provider:'backboard',facts:{...initialFacts(),end:'2026-09-24T20:00:00-04:00',room:'PK-1140',rsvp:'https://www.meetup.com/club/events/123/',groupPage:''},calendarEnabled:true,discordEnabled:true,calendarTarget:'primary',discordTarget:'marketing'});
 if(!result.ok)throw new Error(result.errors.join());
 await page.route(`**/api/plans/${id}`,route=>route.fulfill({json:result.value}));
 await page.goto('/');await page.evaluate(id=>sessionStorage.setItem('relais-plan',id),id);await page.reload();
 const calendar=page.getByTestId('card-create_calendar_event-0');
 const group=page.getByLabel('Group page URL',{exact:true});
 await expect(group).toHaveAttribute('type','url');
 await expect(calendar.getByRole('button',{name:/^Approve and (send|create)$/})).toBeEnabled();
 await group.fill('2');await expect(group).toHaveAttribute('aria-invalid','true');
 await expect(page.getByText(/Paste the full group page URL/)).toBeVisible();
 await expect(page.getByRole('button',{name:'Save details'})).toBeDisabled();
 await expect(calendar.getByRole('button',{name:/^Approve and (send|create)$/})).toBeDisabled();
 await group.fill('');await expect(page.getByRole('button',{name:'Save details'})).toBeEnabled();
 await expect(calendar.getByRole('button',{name:/^Approve and (send|create)$/})).toBeEnabled();
 await expect(page.getByTestId('card-post_discord-1').getByRole('button',{name:/^Approve and (send|create)$/})).toBeEnabled();
 await expect(calendar).not.toContainText('2026-09-24T');
 await page.screenshot({path:'.data/screenshots/review-ux-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'.data/screenshots/review-ux-phone.png',fullPage:true});
 await page.getByLabel('End date and time',{exact:true}).fill('2026-09-24T15:00');
 await expect(page.getByText('The end must be after the start. Check the selected date too.')).toBeVisible();
 await expect(page.getByRole('button',{name:'Save details'})).toBeDisabled();
 await page.getByRole('button',{name:'Discard changes',exact:true}).click();
 await page.getByTestId('card-post_discord-1').getByRole('button',{name:'Edit',exact:true}).click();
 const editor=page.getByRole('dialog');
 expect(await editor.locator('textarea').evaluateAll(inputs=>inputs.some(input=>['📅','📍'].includes((input as HTMLTextAreaElement).value.trim())))).toBe(false);
});
