import { useEffect, useRef, useState } from 'react';
import { factKeys, factsSchema, labels, type Action, type Facts, type Plan } from '../core/model';
import { fixturePrompts } from '../core/fixtures';
const fields:Record<keyof Facts,string>={title:'Titre',dateLabel:'Date affichée',start:'Début (ISO avec fuseau)',end:'Fin (ISO avec fuseau)',room:'Salle',rsvp:'Lien RSVP',groupPage:'Page du groupe',audience:'Public',technicalName:'Terme technique'};
const statuses:Record<Action['status'],string>={proposed:'À revoir',approved:'Approuvé',rejected:'Rejeté',executing:'En cours',executed:'Exécuté',failed:'Échec',unknown:'À vérifier'};
type Audit={id:string;at:string;event:string;detail:string;actionId?:string};
export function App(){
 const [token,setToken]=useState(()=>sessionStorage.getItem('relais-token')||'');
 const [status,setStatus]=useState<{authRequired:boolean;liveReady:boolean;sideEffects:boolean}|null>(null);
 const [prompt,setPrompt]=useState(fixturePrompts[0]);const [mode,setMode]=useState<'scripted'|'backboard'>('scripted');
 const [plan,setPlan]=useState<Plan|null>(null);const [facts,setFacts]=useState<Facts>(factsSchema.parse({}));
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [fallback,setFallback]=useState(false);const [logOpen,setLogOpen]=useState(false);const [logs,setLogs]=useState<Audit[]>([]);
 const [question,setQuestion]=useState('Quand organiser le prochain atelier ?');const [answer,setAnswer]=useState<{text:string;citations:{id:string;title:string;date:string;attendance:number}[];synthetic:boolean}|null>(null);
 const [editor,setEditor]=useState<string|null>(null);const [wireText,setWireText]=useState('');const [copied,setCopied]=useState('');
 const seq=useRef(0);const clientId=useRef(crypto.randomUUID());
 useEffect(()=>{fetch('/api/status').then(r=>r.json()).then(setStatus).catch(()=>setError('Serveur indisponible.'));},[]);
 async function api(path:string,body?:unknown){const r=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Requête refusée.');return data;}
 function accept(p:Plan){setPlan(p);setFacts(p.facts);sessionStorage.setItem('relais-plan',p.id);}
 useEffect(()=>{if(!status||status.authRequired&&!token)return;const id=sessionStorage.getItem('relais-plan');if(id)api(`/api/plans/${id}`).then(accept).catch(()=>{});},[status,token]);
 async function run(task:()=>Promise<void>){setBusy(true);setError('');try{await task();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function generate(provider=mode){await run(async()=>{setFallback(false);try{const p=await api('/api/plan',{prompt,provider,clientId:clientId.current,seq:++seq.current,...(provider==='backboard'?{facts:{...facts,title:facts.title||prompt}}:{})});accept(p);setAnswer(null);}catch(e){setFallback(true);throw e;}});}
 async function operate(a:Action,type:string){await run(async()=>{accept(await api(`/api/plans/${plan!.id}/ops`,{type,actionId:a.id,expectedHash:a.payloadHash}));});}
 async function saveFacts(){await run(async()=>accept(await api(`/api/plans/${plan!.id}/ops`,{type:'edit',facts,expectedRevision:plan!.revision})));}
 async function saveDraft(){await run(async()=>{accept(await api(`/api/plans/${plan!.id}/ops`,{type:'edit',actionId:editor,wire:JSON.parse(wireText),expectedRevision:plan!.revision}));setEditor(null);});}
 async function openLog(){await run(async()=>{setLogs(await api('/api/log'));setLogOpen(true);});}
 function editorFields(value:unknown,path:string[]=[]):{path:string[];value:string}[]{
  if(typeof value==='string')return [{path,value}];
  if(value&&typeof value==='object')return Object.entries(value).filter(([k])=>!['type','channel','recipientRole'].includes(k)).flatMap(([k,v])=>editorFields(v,[...path,k]));
  return [];
 }
 function changeField(path:string[],value:string){const draft=JSON.parse(wireText);let part=draft;for(const k of path.slice(0,-1))part=part[k];part[path[path.length-1]]=value;setWireText(JSON.stringify(draft));}
 const editLabels:Record<string,string>={title:'Titre',text:'Texte',description:'Description',start:'Début',end:'Fin',location:'Lieu',hook:'Accroche',whyUseful:'Pourquoi participer',audience:'Pour qui',bring:'Quoi apporter',details:'Détails',registrationCTA:'Invitation à s’inscrire'};
 const reviewed=plan?.actions.filter(a=>a.status!=='proposed').length||0;
 const need=plan?[...new Set(plan.actions.flatMap(a=>a.needsInput))]:[];
 return <div className="shell">
  <header><a className="brand" href="/" aria-label="Relais accueil"><span className="brand-mark">r.</span>relais<span className="brand-dot">✳</span></a><div className="header-right"><span className={`badge ${plan?.provider==='backboard'?'live':''}`}>{plan?.provider==='backboard'?'LIVE':'SCRIPTED'}</span><span className="execution-label">{plan?.provider==='backboard'?'Actions réelles sur approbation':'Exécutions simulées'}</span><button className="quiet" onClick={openLog} disabled={busy}>Journal ↗</button></div></header>
  <main>
   <section className="intro"><div><p className="eyebrow">AWS STUDENT BUILDER GROUP AT UQAM</p><h1>Une idée.<br/><span>On prend le relais.</span></h1><p className="lede">L’IA propose. Tu décides.<br/>Prépare ton prochain événement, un brouillon à la fois.</p></div><div className="intro-note"><span>01 / ORGANISER ENSEMBLE</span><p>Apprendre · Construire · Connecter.</p><small>Rien n’est publié sans ton approbation.</small></div></section>
   {status?.authRequired&&<details className="auth"><summary>Accès organisateur {token?'· jeton enregistré pour cet onglet':''}</summary><label>Jeton organisateur<input type="password" autoComplete="off" value={token} onChange={e=>{setToken(e.target.value);sessionStorage.setItem('relais-token',e.target.value);}} placeholder="Coller le jeton serveur"/></label></details>}
   <section className="composer"><div className="section-heading"><h2>Qu’est-ce qu’on organise ?</h2><select aria-label="Fournisseur" value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="scripted">Démo scripted</option><option value="backboard" disabled={!status?.liveReady}>Backboard {status?.liveReady?'live':'non configuré'}</option></select></div><label className="sr-only" htmlFor="event-idea">Idée d’événement</label><textarea id="event-idea" value={prompt} onChange={e=>setPrompt(e.target.value)} rows={3}/><div className="composer-bottom"><div className="examples"><span>ESSAYER</span>{['Terraform','Intro cloud','Certification'].map((x,i)=><button key={x} className="chip" disabled={busy} onClick={()=>{setPrompt(fixturePrompts[i]);setMode('scripted');}}>{x} ↗</button>)}</div><button className="primary" disabled={busy} onClick={()=>generate()}>{busy?'Un instant…':'Proposer un plan ↗'}</button></div><small className="muted">{mode==='scripted'?'Trois scénarios déterministes · aucune requête externe · horloge du 19 septembre 2026':'Les faits manquants resteront à compléter. Aucun fait ne sera inventé.'}</small></section>
   {error&&<div role="alert" className="error">{error}{fallback&&<button onClick={()=>{setPrompt(fixturePrompts[0]);setMode('scripted');}} disabled={busy}>Choisir l’exemple scripted</button>}{fallback&&fixturePrompts.includes(prompt)&&<button disabled={busy} onClick={()=>generate('scripted')}>Utiliser la démo scripted</button>}</div>}
   {plan&&<>
    <section className="plan-heading"><div><p className="eyebrow">TON PLAN · RÉVISION {plan.revision}</p><h2>{plan.actions.length} propositions. À toi de jouer.</h2></div><span className="progress">{reviewed}/{plan.actions.length} revues</span></section>
    <details className="facts-panel" open={need.length>0}><summary>Les détails de l’événement <span>{need.length?`${need.length} faits à compléter`:'Faits confirmés'}</span></summary><p className="muted">Ces faits alimentent les brouillons. Toute modification annule l’approbation des cartes concernées.</p><div className="facts-grid">{factKeys.map(k=><label key={k}>{fields[k]}{need.includes(k)&&<span className="required"> À compléter</span>}<input aria-label={fields[k]} value={facts[k]} placeholder={k==='end'?'2026-09-24T20:00:00-04:00':k==='rsvp'?'https://…':''} onChange={e=>setFacts({...facts,[k]:e.target.value})}/></label>)}</div><button className="secondary" disabled={busy} onClick={saveFacts}>Confirmer les faits</button></details>
    <div className="workspace"><section className="cards" aria-label="Actions proposées">{plan.actions.map((a,i)=><article className={`card ${a.status==='rejected'?'rejected':''}`} key={a.id} data-testid={`card-${a.type}-${i}`}><div className="card-top"><span className="card-number">{String(i+1).padStart(2,'0')}</span><div><h3>{labels[a.type]}</h3><span className="muted">{a.type==='draft_dm'?String(a.payload.recipientRole):a.destination}</span></div><span className={`status ${a.status}`}>{statuses[a.status]}</span></div><div className="card-content"><div className="tags"><span>{a.capability==='draft'?'Brouillon, non publié':plan.provider==='scripted'?'Action simulée':'Action réelle'}</span>{a.needsInput.length>0&&<span className="missing">À compléter : {a.needsInput.map(x=>fields[x as keyof Facts]).join(', ')}</span>}</div><pre className="draft">{a.text}</pre>{a.type==='create_calendar_event'&&<p className="preference">↳ Préférence enregistrée : lundi à 16 h (notes de septembre, fixture). La date demandée est conservée.</p>}{a.receipt&&<p className="receipt">✓ {a.receipt.simulated?'Simulation seulement, aucune action externe':'Exécution enregistrée'} · {a.receipt.provider} · {a.receipt.id}{a.receipt.url&&/^https:\/\//.test(a.receipt.url)&&<> · <a href={a.receipt.url} target="_blank" rel="noreferrer">Voir ↗</a></>}</p>}{a.error&&<p className="error">{a.error}</p>}</div><footer className="card-footer"><button className="quiet" disabled={busy||['executed','executing','unknown'].includes(a.status)} onClick={()=>{setEditor(a.id);setWireText(JSON.stringify(a.wire,null,2));}}>Modifier</button><button className="quiet" onClick={async()=>{try{await navigator.clipboard.writeText(a.text);setCopied(a.id);}catch{setError('Copie indisponible. Sélectionnez le texte du brouillon.');}}}>{copied===a.id?'Copié ✓':'Copier'}</button><div className="decisions"><button className="reject" disabled={busy||!['proposed','approved','failed'].includes(a.status)} onClick={()=>operate(a,'reject')}>Rejeter</button><button className="approve" disabled={busy||a.needsInput.length>0||!['proposed','failed'].includes(a.status)} onClick={()=>operate(a,'approve')}>{a.capability==='draft'?'Valider le brouillon':'Approuver'}</button></div></footer>{a.status==='unknown'&&<div className="unknown"><button onClick={()=>operate(a,'confirm_posted')}>J’ai vérifié, c’est publié</button><button onClick={()=>operate(a,'confirm_not_posted')}>J’ai vérifié, rien de visible</button><small>Aucune relance automatique. Une réponse tardive reste possible.</small></div>}</article>)}</section>
    <aside><section className="aside-box"><p className="eyebrow">APRÈS L’ÉVÉNEMENT</p><h3>Garder le lien.</h3><p>{plan.followupPreview}</p><span className="badge subtle">NON PROGRAMMÉ</span></section><section className="aside-box history"><p className="eyebrow">APPRENDRE DU PASSÉ</p><h3>Et la prochaine fois ?</h3><p className="muted">Six événements fictifs pour explorer les suggestions. Aucune fréquentation réelle du club.</p><label className="sr-only" htmlFor="question">Question historique</label><textarea id="question" value={question} onChange={e=>setQuestion(e.target.value)} rows={3}/><button className="secondary" disabled={busy} onClick={()=>run(async()=>setAnswer(await api('/api/ask',{question})))}>Consulter l’historique ↗</button>{answer&&<div className="answer"><span className="badge subtle">DONNÉES SYNTHÉTIQUES · SCRIPTED</span><p>{answer.text}</p>{answer.citations.map(c=><div className="citation" key={c.id}><strong>{c.id}</strong><span>{c.title} · {c.date} · {c.attendance} personnes</span></div>)}</div>}</section><p className="aside-footnote">Un brouillon reste un brouillon.<br/>Tu gardes le dernier mot.</p></aside></div>
   </>}
   {!plan&&<div className="empty"><span>✳</span><h2>Moins de copier-coller.<br/>Plus de moments ensemble.</h2><p>Calendar, Discord et les brouillons de tes canaux,<br/>dans un seul plan à revoir.</p></div>}
  </main><footer className="site-footer"><span>relais · construit pour les communautés étudiantes</span><span>Apprendre · Construire · Connecter.</span></footer>
  {logOpen&&<div className="overlay" onClick={()=>setLogOpen(false)}><section role="dialog" aria-modal="true" aria-label="Journal des opérations" className="drawer" onClick={e=>e.stopPropagation()}><div className="section-heading"><h2>Le journal</h2><button onClick={()=>setLogOpen(false)}>Fermer</button></div><p className="muted">Propositions, décisions et résultats. Dernières opérations en premier.</p>{logs.length===0?<p>Aucune opération.</p>:logs.map(l=><div className="log-entry" key={l.id}><time>{new Date(l.at).toLocaleTimeString('fr-CA')}</time><strong>{l.event}</strong><p>{l.detail}</p></div>)}</section></div>}
  {editor&&<div className="overlay"><section role="dialog" aria-modal="true" aria-label="Modifier le brouillon" className="editor"><div className="section-heading"><h2>Modifier le brouillon</h2><button onClick={()=>setEditor(null)}>Fermer</button></div><p>Conserve les références {'{{fact.key}}'} pour les faits. Aucun chiffre, lien ou mention dans le texte libre.</p>{editorFields(JSON.parse(wireText)).map(field=><label className="edit-field" key={field.path.join('.')}><span>{editLabels[field.path.at(-1)!]||'Au programme'}</span><textarea aria-label={editLabels[field.path.at(-1)!]||'Au programme'} value={field.value} onChange={e=>changeField(field.path,e.target.value)} rows={field.value.length>150?6:2}/></label>)}{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy} onClick={saveDraft}>Enregistrer pour revue</button></section></div>}
 </div>;
}
