// Translate interface feedback only. Never apply this to drafts or conversation content.
const messages: Record<string, string> = {
  "Actions externes désactivées.": "External actions are disabled.",
  "Les actions externes sont désactivées.": "External actions are disabled.",
  "Fournisseur indisponible. Réessayez.": "Provider unavailable. Try again.",
  "Jeton organisateur requis.": "Organizer token required.",
  "Opération invalide.": "Invalid operation.",
  "Limite atteinte. Réessayez dans une minute.": "Limit reached. Try again in a minute.",
  "Requête périmée.": "Request expired.",
  "Réponse périmée ignorée.": "Outdated response ignored.",
  "Configuration modifiée. Générez un nouveau plan.": "Configuration changed. Create a new plan.",
  "Action périmée. Rechargez le plan.": "This action is out of date. Reload the plan.",
  "Plan périmé. Rechargez avant de modifier.": "This plan is out of date. Reload before editing.",
  "Approbation périmée. Relisez cette action.": "Approval is out of date. Review this action again.",
  "Complétez les faits manquants avant approbation.": "Add the missing details before approving.",
  "Une action exécutée ou incertaine est immuable.": "An executed action or one awaiting verification cannot be edited.",
  "Backboard non configuré. Le plan actuel est conservé.": "Backboard is not configured. Your current plan is preserved.",
  "Backboard non configuré. La conversation est conservée.": "Backboard is not configured. Your conversation is preserved.",
  "Documents non indexés.": "Context documents are not indexed yet.",
  "Plafond de coût atteint.": "The session cost limit has been reached.",
  "Backboard indisponible.": "Backboard is unavailable.",
  "Backboard a refusé la requête.": "Backboard rejected the request.",
  "Un brouillon contient encore des informations non validées après correction. Le plan précédent est conservé. Réessaie ou prépare un message Discord.": "A draft still contains unvalidated details after correction. Your previous plan is preserved. Try again or prepare a Discord message.",
  "Backboard a dépassé le délai de réponse. Aucun nouveau plan n’a été enregistré et aucune action n’a été exécutée. Pour tester Discord sans génération, choisis « Message Discord ».": "Backboard timed out. No new plan was saved and no action was executed. To test Discord without generation, choose Discord message.",
  "Le service de conversation est indisponible. Réessaie dans un instant.": "Chat is unavailable. Try again shortly.",
  "Réponse de conversation invalide. Aucun brouillon ni action enregistré.": "Invalid chat response. No draft or action was saved.",
  "Conversation introuvable.": "Conversation not found.",
  "Conversation modifiée ou réponse en cours. Recharge la conversation.": "The conversation changed or a reply is in progress. Reload the conversation.",
  "Cette conversation a atteint sa limite. Démarre une nouvelle conversation.": "This conversation reached its limit. Start a new conversation.",
  "Conversation modifiée. Rechargez-la avant de préparer le message.": "The conversation changed. Reload it before preparing the message.",
  "Complétez les placeholders dans la conversation avant de préparer le message.": "Fill in the missing details in the conversation before preparing the message.",
  "Le message Discord doit contenir entre un et deux mille caractères. Demandez une version plus courte.": "Discord messages must contain 1 to 2,000 characters. Ask for a shorter version.",
  "La connexion ou la destination a changé depuis cette proposition. Préparez une nouvelle proposition et relisez sa destination. Aucun envoi tenté.": "The connection or destination changed. Prepare a new proposal and review its destination. No send was attempted.",
  "Composio n’a pas confirmé l’exécution. Vérifiez la destination.": "Composio has not confirmed execution. Check the destination.",
  "Résultat non confirmé. Vérifiez la destination avant toute autre action.": "Result unconfirmed. Check the destination before taking another action.",
  "Impossible de vérifier le compte Composio. Aucun nouvel envoi tenté.": "Could not verify the Composio account. No new send was attempted.",
  "Compte Composio inactif ou utilisateur absent. Aucun nouvel envoi tenté.": "The Composio account is inactive or its user is missing. No new send was attempted.",
  "Permissions Google Calendar insuffisantes. Reconnectez le compte dans Composio avec les autorisations de lecture du calendrier et de création d’événements.": "Google Calendar permissions are insufficient. Reconnect the account in Composio with permission to read calendars and create events.",
  "Discord ne trouve pas ce salon ou le bot ne peut pas y accéder. Vérifiez l’identifiant du salon et les permissions du bot.": "Discord cannot find this channel or the bot cannot access it. Check the channel ID and bot permissions.",
  "Le bot Discord n’a pas les permissions nécessaires dans ce salon.": "The Discord bot needs permission to access and post in this channel.",
  "Aucun identifiant de reçu enregistré pour cette tentative. Vérifiez directement la destination. Aucun nouvel envoi.": "No receipt ID was saved for this attempt. Check the destination directly. Nothing was sent again.",
  "Vérification Composio indisponible. Aucun nouvel envoi.": "Composio verification is unavailable. Nothing was sent again.",
  "Le reçu ne correspond pas à cette tentative. Aucun nouvel envoi.": "The receipt does not match this attempt. Nothing was sent again.",
  "Composio ne confirme pas de réussite pour cette tentative. Vérifiez la destination. Aucun nouvel envoi.": "Composio has not confirmed success. Check the destination. Nothing was sent again.",
  "Une exécution est déjà en cours.": "An action is already running.",
  "Collez l’URL complète de la page du groupe, par exemple https://www.linkedin.com/company/nom-du-groupe/. Vous pouvez laisser ce champ vide.": "Paste the full group page URL, for example https://www.linkedin.com/company/your-group/. You can leave this field blank.",
  "Collez un lien d’inscription complet commençant par https://. Vous pouvez laisser ce champ vide.": "Paste a full registration URL starting with https://. You can leave this field blank.",
  "Choisissez une date et une heure valides.": "Choose a valid date and time.",
  "La fin doit être après le début. Vérifiez aussi la date choisie.": "The end must be after the start. Check the selected date too.",
  "Remplacez le tiret cadratin par un tiret simple.": "Replace the em dash with a hyphen.",
  "Ce champ est trop long.": "This field is too long.",
  "Choisis une date et une heure complètes.": "Choose a complete date and time.",
  "Date invalide.": "Invalid date.",
  "Cette heure n’existe pas à Montréal lors du changement d’heure. Choisis une autre heure.": "This time does not exist in Montreal because of daylight saving time. Choose another time.",
  "Cette heure se produit deux fois lors du changement d’heure. Choisis une heure avant ou après cette période.": "This time occurs twice when daylight saving time ends. Choose a time before or after this period.",
  "Plan introuvable.": "Plan not found.",
  "Plan requis.": "A plan is required.",
  "Action inconnue.": "Unknown action.",
  "Action introuvable.": "Action not found.",
  "Action non disponible pour approbation.": "This action cannot be approved.",
  "Cette action ne peut plus être rejetée.": "This action can no longer be rejected.",
  "Exécution non approuvée.": "Execution is not approved.",
  "Action non approuvée.": "This action is not approved.",
  "Résultat inattendu.": "Unexpected result.",
  "Reçu requis.": "A receipt is required.",
  "Échec inattendu.": "Unexpected failure.",
  "Référence de fait inconnue.": "Unknown detail reference.",
  "Les tirets cadratins sont interdits.": "Em dashes are not supported.",
  "Références Calendar invalides.": "Invalid Calendar detail references.",
  "Calendar nécessite des références de faits pour les horaires et le lieu.": "Calendar requires saved detail references for the time and location.",
  "Snapshot normalisé invalide.": "Invalid proposal snapshot.",
  "chiffre, lien, mention ou placeholder hors référence {{fact.key}}.": "a number, link, mention, or placeholder is outside a saved detail reference.",
  "Origine refusée.": "Request origin refused.",
  "Origine invalide.": "Invalid request origin.",
  "HTTPS requis pour les opérations authentifiées.": "HTTPS is required for authenticated operations.",
  "JSON requis.": "JSON is required.",
  "Configurez une destination Discord avant de préparer ce message.": "Configure a Discord destination before preparing this message.",
  "Ce plan de démonstration est archivé. Créez un nouveau plan.": "This demo plan is archived. Create a new plan.",
  "Type et identité immuables.": "The action type and identity cannot be changed.",
  "Cette action n’est pas incertaine.": "This action is not awaiting verification.",
  "Route inconnue.": "Unknown route.",
  "Erreur inconnue.": "Unknown error.",
  "Démarre une nouvelle conversation pour changer de fournisseur.": "Start a new conversation to change providers.",
  "Cette réponse ne contient pas de brouillon.": "This reply does not contain a draft.",
  "Configurez un plafond et un coût maximal vérifié avant les appels payants.": "Configure a spending limit and a verified maximum request cost before making paid calls.",
  "Reçu fournisseur absent.": "Provider receipt missing.",
  "Discord : texte trop long.": "Discord message is too long.",
  "Webhook non autorisé.": "Webhook not allowed.",
  "Discord : résultat non confirmé.": "Discord result unconfirmed.",
  "Discord : reçu absent.": "Discord receipt missing.",
  "Aucun exécuteur pour ce brouillon.": "This draft has no publishing integration.",
  "Action absente ou périmée.": "This action is missing or out of date.",
  "Action non disponible.": "Action unavailable.",
  "Action absente, périmée ou non vérifiable.": "This action is missing, out of date, or cannot be verified.",
  "Action modifiée pendant la vérification.": "The action changed during verification.",
  "réponse consultative, aucune exécution": "advisory reply, no execution",
  "en attente d’approbation": "awaiting approval",
  "Faits ou brouillon révisés": "Details or draft updated",
  "Déclaration manuelle de l’organisateur, pas un reçu fournisseur.": "Manually reported by the organizer; no provider receipt.",
  "Simulation demandée": "Simulation requested",
  "Tentative externe approuvée": "External action approved",
  "succès confirmé": "success confirmed",
  "résultat non confirmé": "result unconfirmed",
  "Brouillon Discord manuel": "Manual Discord draft",
  "Composio a répondu HTTP": "Composio returned HTTP",
  "Vérifiez la connexion et la destination avant toute autre tentative.": "Check the connection and destination before trying again."
};
export function uiText(message = ''): string {
  let result = message;
  for (const [original, translated] of Object.entries(messages)) result = result.replaceAll(original, translated);
  return result;
}
